spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  config:
    import: optional:classpath:application-secret.yml

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB